In [22]:
import pandas as pd 
import numpy as np

In [35]:
f  = pd.read_csv('data/charting-m-stats-Overview.csv', delimiter= ',')
f

,match_id,player,set,serve_pts,aces,dfs,first_in,first_won,second_in,second_won,bk_pts,bp_saved,return_pts,return_pts_won,winners,winners_fh,winners_bh,unforced,unforced_fh,unforced_bh
0,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,1,Total,69,2,1,32,25,37,21,5,4,63,36,28,10,16,16,6,9
1,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,2,Total,63,2,2,41,20,22,7,12,4,69,23,14,8,4,26,15,9
2,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,1,1,26,2,0,15,10,11,6,2,1,18,13,10,3,5,6,2,4
3,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,2,1,18,0,0,11,3,7,2,3,0,26,10,4,2,2,10,7,3
4,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,1,2,24,0,0,10,9,14,8,1,1,26,10,9,3,6,6,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19735,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,2,1,40,3,0,22,13,18,10,7,6,27,12,10,4,3,13,6,7
19736,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,1,2,30,3,2,22,15,8,4,4,3,23,15,9,4,2,9,3,4
19737,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,2,2,23,2,0,14,6,9,2,4,1,30,11,6,1,3,13,8,5
19738,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,1,3,30,2,2,13,10,17,7,3,2,17,12,9,4,3,5,1,2
19739,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,2,3,17,0,1,9,3,8,2,4,1,30,13,7,5,2,13,7,5

In [2]:
df = pd.read_csv('data/charting-m-stats-Overview.csv', delimiter= ',')
df[['tourney_date', 'sm','tourney_name','sm2','player1','player2']] = df['match_id'].str.split('-', 6, expand=True)
# df.rename(columns = {'first_in':'l_1stIn', 'first_won':'l_1stWon','second_won' : 'l_2ndWon', 'aces' : 'l_ace'}, inplace = True)
df['tourney_date'] = df['tourney_date'].apply(lambda x : int(x)) 
df = df.loc[df['tourney_date'] > 20050000 , :]
df =  df[(df['set'] == 'Total') & (df['player'] == 1)] 
# df[df['l_1stIn' , 'l_1stWon','l_2ndWon' , 'l_ace']] = df['first_in', 'first_won','second_won' , 'aces' ]
df['l_1stIn'] = df['first_in'] 
df['l_1stWon'] = df['first_won'] 
df['l_2ndWon'] = df['second_won'] 
df['l_ace'] = df['aces'] 
df['l_winners_fh'] = df['winners_fh'] 
df['l_winners_bh'] = df['winners_bh'] 
df['l_unforced_fh'] = df['unforced_fh'] 
df['l_unforced_bh'] = df['unforced_bh'] 
df['l_return_pts_faced'] = df['return_pts'] 
df['l_return_pts_won'] = df['return_pts_won'] 
df.drop(df.columns.to_list()[1:24],axis =1 ,inplace=True)
df

,match_id,player1,player2,l_1stIn,l_1stWon,l_2ndWon,l_ace,l_winners_fh,l_winners_bh,l_unforced_fh,l_unforced_bh,l_return_pts_faced,l_return_pts_won
572,20050221-M-Dubai-SF-Roger_Federer-Andre_Agassi,Roger_Federer,Andre_Agassi,33,25,11,7,10,3,7,9,41,21
578,20050318-M-Indian_Wells_Masters-SF-Roger_Feder...,Roger_Federer,Guillermo_Canas,34,22,13,7,11,5,11,6,47,23
584,20050703-M-Wimbledon-F-Roger_Federer-Andy_Roddick,Roger_Federer,Andy_Roddick,49,40,22,11,20,14,5,15,90,35
592,20050911-M-US_Open-F-Roger_Federer-Andre_Agassi,Roger_Federer,Andre_Agassi,81,60,15,20,26,10,13,26,131,57
602,20060123-M-Australian_Open-QF-David_Nalbandian...,David_Nalbandian,Fabrice_Santoro,46,34,13,2,25,19,10,8,76,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19694,20220704-M-Wimbledon-R16-Rafael_Nadal-Botic_Va...,Rafael_Nadal,Botic_Van_De_Zandschulp,56,41,21,8,8,11,13,9,101,42
19710,20220712-M-Newport-R32-Andy_Murray-Sam_Querrey,Andy_Murray,Sam_Querrey,31,21,7,5,2,2,2,6,38,26
19716,20220712-M-Bastad-R32-Emil_Ruusuvuori-Dominic_...,Emil_Ruusuvuori,Dominic_Thiem,55,31,18,1,11,6,15,19,98,39
19724,20220706-M-Wimbledon-QF-Nick_Kyrgios-Cristian_...,Nick_Kyrgios,Cristian_Garin,81,59,14,17,11,4,21,17,88,32
19732,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,Andy_Murray,Max_Purcell,50,35,16,8,10,7,11,7,80,44

In [3]:
d2 = pd.read_csv('data/charting-m-stats-Overview.csv', delimiter= ',')
d2[['tourney_date', 'sm','tourney_name','sm2','player1','player2']] = d2['match_id'].str.split('-', 6, expand=True)
# df.rename(columns = {'first_in':'l_1stIn', 'first_won':'l_1stWon','second_won' : 'l_2ndWon', 'aces' : 'l_ace'}, inplace = True)
d2['tourney_date'] = d2['tourney_date'].apply(lambda x : int(x)) 
d2 = d2.loc[d2['tourney_date'] > 20050000 , :]
d2 =  d2[(d2['set'] == 'Total') & (d2['player'] == 2)] 
# df[df['l_1stIn' , 'l_1stWon','l_2ndWon' , 'l_ace']] = df['first_in', 'first_won','second_won' , 'aces' ]
d2['w_1stIn'] = d2['first_in'] 
d2['w_1stWon'] = d2['first_won'] 
d2['w_2ndWon'] = d2['second_won'] 
d2['w_ace'] = d2['aces'] 
d2['w_winners_fh'] = d2['winners_fh'] 
d2['w_winners_bh'] = d2['winners_bh'] 
d2['w_unforced_fh'] = d2['unforced_fh'] 
d2['w_unforced_bh'] = d2['unforced_bh'] 
d2['w_return_pts_faced'] = d2['return_pts'] 
d2['w_return_pts_won'] = d2['return_pts_won'] 
d2.drop(d2.columns.to_list()[1:24],axis =1 ,inplace=True)
d2

,match_id,player1,player2,w_1stIn,w_1stWon,w_2ndWon,w_ace,w_winners_fh,w_winners_bh,w_unforced_fh,w_unforced_bh,w_return_pts_faced,w_return_pts_won
573,20050221-M-Dubai-SF-Roger_Federer-Andre_Agassi,Roger_Federer,Andre_Agassi,23,10,10,1,2,1,8,8,51,15
579,20050318-M-Indian_Wells_Masters-SF-Roger_Feder...,Roger_Federer,Guillermo_Canas,27,14,10,2,6,2,7,8,56,21
585,20050703-M-Wimbledon-F-Roger_Federer-Andy_Roddick,Roger_Federer,Andy_Roddick,62,42,13,7,6,3,11,8,79,17
593,20050911-M-US_Open-F-Roger_Federer-Andre_Agassi,Roger_Federer,Andre_Agassi,78,45,29,6,14,8,12,17,107,32
603,20060123-M-Australian_Open-QF-David_Nalbandian...,David_Nalbandian,Fabrice_Santoro,53,28,5,4,7,5,4,9,64,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19695,20220704-M-Wimbledon-R16-Rafael_Nadal-Botic_Va...,Rafael_Nadal,Botic_Van_De_Zandschulp,62,42,17,12,10,8,19,20,88,26
19711,20220712-M-Newport-R32-Andy_Murray-Sam_Querrey,Andy_Murray,Sam_Querrey,15,9,3,2,3,4,14,14,41,13
19717,20220712-M-Bastad-R32-Emil_Ruusuvuori-Dominic_...,Emil_Ruusuvuori,Dominic_Thiem,69,45,14,7,12,12,27,14,89,40
19725,20220706-M-Wimbledon-QF-Nick_Kyrgios-Cristian_...,Nick_Kyrgios,Cristian_Garin,63,43,13,2,16,8,15,13,114,41
19733,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,Andy_Murray,Max_Purcell,45,22,14,5,10,8,21,17,87,36

In [4]:
seleted_rows = (d['loser_name'] == 'Arthur Rinderknech' ) & (d['winner_name'] == 'Thanasi Kokkinakis') #df['Job Type']=='White-collar'
display(d.loc[seleted_rows,:])

NameError: name 'd' is not defined

In [6]:
data_m = pd.merge(df,                         
                          d2,
                          on = ['player1','player2','match_id'],
                          how = "outer")
display(data_m)  
data_m.info()

,match_id,player1,player2,l_1stIn,l_1stWon,l_2ndWon,l_ace,l_winners_fh,l_winners_bh,l_unforced_fh,...,w_1stIn,w_1stWon,w_2ndWon,w_ace,w_winners_fh,w_winners_bh,w_unforced_fh,w_unforced_bh,w_return_pts_faced,w_return_pts_won
0,20050221-M-Dubai-SF-Roger_Federer-Andre_Agassi,Roger_Federer,Andre_Agassi,33,25,11,7,10,3,7,...,23,10,10,1,2,1,8,8,51,15
1,20050318-M-Indian_Wells_Masters-SF-Roger_Feder...,Roger_Federer,Guillermo_Canas,34,22,13,7,11,5,11,...,27,14,10,2,6,2,7,8,56,21
2,20050703-M-Wimbledon-F-Roger_Federer-Andy_Roddick,Roger_Federer,Andy_Roddick,49,40,22,11,20,14,5,...,62,42,13,7,6,3,11,8,79,17
3,20050911-M-US_Open-F-Roger_Federer-Andre_Agassi,Roger_Federer,Andre_Agassi,81,60,15,20,26,10,13,...,78,45,29,6,14,8,12,17,107,32
4,20060123-M-Australian_Open-QF-David_Nalbandian...,David_Nalbandian,Fabrice_Santoro,46,34,13,2,25,19,10,...,53,28,5,4,7,5,4,9,64,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,20220704-M-Wimbledon-R16-Rafael_Nadal-Botic_Va...,Rafael_Nadal,Botic_Van_De_Zandschulp,56,41,21,8,8,11,13,...,62,42,17,12,10,8,19,20,88,26
2088,20220712-M-Newport-R32-Andy_Murray-Sam_Querrey,Andy_Murray,Sam_Querrey,31,21,7,5,2,2,2,...,15,9,3,2,3,4,14,14,41,13
2089,20220712-M-Bastad-R32-Emil_Ruusuvuori-Dominic_...,Emil_Ruusuvuori,Dominic_Thiem,55,31,18,1,11,6,15,...,69,45,14,7,12,12,27,14,89,40
2090,20220706-M-Wimbledon-QF-Nick_Kyrgios-Cristian_...,Nick_Kyrgios,Cristian_Garin,81,59,14,17,11,4,21,...,63,43,13,2,16,8,15,13,114,41
2091,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,Andy_Murray,Max_Purcell,50,35,16,8,10,7,11,...,45,22,14,5,10,8,21,17,87,36

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2092 entries, 0 to 2091
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   match_id            2092 non-null   object
 1   player1             2092 non-null   object
 2   player2             2092 non-null   object
 3   l_1stIn             2092 non-null   int64
 4   l_1stWon            2092 non-null   int64
 5   l_2ndWon            2092 non-null   int64
 6   l_ace               2092 non-null   int64
 7   l_winners_fh        2092 non-null   int64
 8   l_winners_bh        2092 non-null   int64
 9   l_unforced_fh       2092 non-null   int64
 10  l_unforced_bh       2092 non-null   int64
 11  l_return_pts_faced  2092 non-null   int64
 12  l_return_pts_won    2092 non-null   int64
 13  w_1stIn             2092 non-null   int64
 14  w_1stWon            2092 non-null   int64
 15  w_2ndWon            2092 non-null   int64
 16  w_ace               2092 non-null   int64
 17  w_winners_fh        2092 non-null   int64
 18  w_winners_bh        2092 non-null   int64
 19  w_unforced_fh       2092 non-null   int64
 20  w_unforced_bh       2092 non-null   int64
 21  w_return_pts_faced  2092 non-null   int64
 22  w_return_pts_won    2092 non-null   int64
dtypes: int64(20), object(3)
memory usage: 392.2+ KB

In [7]:
d = pd.read_csv('data/atp_matches_2005-2022.csv')

C:\Users\HP\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (9,17) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [8]:
ndf = data_m.copy()
ndf.rename(columns = {'player1':'loser_name', 'player2':'winner_name'}, inplace = True)
ndf.loc[:,['winner_name','loser_name']]=ndf.loc[:,['winner_name','loser_name']].applymap(lambda x: x.replace('_',' ') ) #for multiple columns
ndf

,match_id,loser_name,winner_name,l_1stIn,l_1stWon,l_2ndWon,l_ace,l_winners_fh,l_winners_bh,l_unforced_fh,...,w_1stIn,w_1stWon,w_2ndWon,w_ace,w_winners_fh,w_winners_bh,w_unforced_fh,w_unforced_bh,w_return_pts_faced,w_return_pts_won
0,20050221-M-Dubai-SF-Roger_Federer-Andre_Agassi,Roger Federer,Andre Agassi,33,25,11,7,10,3,7,...,23,10,10,1,2,1,8,8,51,15
1,20050318-M-Indian_Wells_Masters-SF-Roger_Feder...,Roger Federer,Guillermo Canas,34,22,13,7,11,5,11,...,27,14,10,2,6,2,7,8,56,21
2,20050703-M-Wimbledon-F-Roger_Federer-Andy_Roddick,Roger Federer,Andy Roddick,49,40,22,11,20,14,5,...,62,42,13,7,6,3,11,8,79,17
3,20050911-M-US_Open-F-Roger_Federer-Andre_Agassi,Roger Federer,Andre Agassi,81,60,15,20,26,10,13,...,78,45,29,6,14,8,12,17,107,32
4,20060123-M-Australian_Open-QF-David_Nalbandian...,David Nalbandian,Fabrice Santoro,46,34,13,2,25,19,10,...,53,28,5,4,7,5,4,9,64,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,20220704-M-Wimbledon-R16-Rafael_Nadal-Botic_Va...,Rafael Nadal,Botic Van De Zandschulp,56,41,21,8,8,11,13,...,62,42,17,12,10,8,19,20,88,26
2088,20220712-M-Newport-R32-Andy_Murray-Sam_Querrey,Andy Murray,Sam Querrey,31,21,7,5,2,2,2,...,15,9,3,2,3,4,14,14,41,13
2089,20220712-M-Bastad-R32-Emil_Ruusuvuori-Dominic_...,Emil Ruusuvuori,Dominic Thiem,55,31,18,1,11,6,15,...,69,45,14,7,12,12,27,14,89,40
2090,20220706-M-Wimbledon-QF-Nick_Kyrgios-Cristian_...,Nick Kyrgios,Cristian Garin,81,59,14,17,11,4,21,...,63,43,13,2,16,8,15,13,114,41
2091,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,Andy Murray,Max Purcell,50,35,16,8,10,7,11,...,45,22,14,5,10,8,21,17,87,36

In [9]:
data_merge_all = pd.merge(d,                         
                          ndf,
                          on = ['l_1stIn','l_1stWon','l_2ndWon' , 'l_ace','winner_name','loser_name'],
                          how = "right")
display(data_merge_all)

,Unnamed: 0,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,...,w_1stIn_y,w_1stWon_y,w_2ndWon_y,w_ace_y,w_winners_fh,w_winners_bh,w_unforced_fh,w_unforced_bh,w_return_pts_faced,w_return_pts_won
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23,10,10,1,2,1,8,8,51,15
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27,14,10,2,6,2,7,8,56,21
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62,42,13,7,6,3,11,8,79,17
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,78,45,29,6,14,8,12,17,107,32
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53,28,5,4,7,5,4,9,64,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62,42,17,12,10,8,19,20,88,26
2088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,9,3,2,3,4,14,14,41,13
2089,51217.0,2022-0316,Bastad,Clay,32.0,A,20220711.0,275.0,106233.0,NaN,...,69,45,14,7,12,12,27,14,89,40
2090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63,43,13,2,16,8,15,13,114,41
2091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45,22,14,5,10,8,21,17,87,36

In [10]:
data_merge_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2092 entries, 0 to 2091
Data columns (total 67 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          486 non-null    float64
 1   tourney_id          486 non-null    object
 2   tourney_name        486 non-null    object
 3   surface             486 non-null    object
 4   draw_size           486 non-null    float64
 5   tourney_level       486 non-null    object
 6   tourney_date        486 non-null    float64
 7   match_num           486 non-null    float64
 8   winner_id           486 non-null    float64
 9   winner_seed         318 non-null    object
 10  winner_entry        56 non-null     object
 11  winner_name         2092 non-null   object
 12  winner_hand         486 non-null    object
 13  winner_ht           485 non-null    float64
 14  winner_ioc          486 non-null    object
 15  winner_age          486 non-null    float64
 16  loser_id            486 non-null    float64
 17  loser_seed          276 non-null    object
 18  loser_entry         59 non-null     object
 19  loser_name          2092 non-null   object
 20  loser_hand          486 non-null    object
 21  loser_ht            483 non-null    float64
 22  loser_ioc           486 non-null    object
 23  loser_age           486 non-null    float64
 24  score               486 non-null    object
 25  best_of             486 non-null    float64
 26  round               486 non-null    object
 27  minutes             470 non-null    float64
 28  w_ace_x             486 non-null    float64
 29  w_df                486 non-null    float64
 30  w_svpt              486 non-null    float64
 31  w_1stIn_x           486 non-null    float64
 32  w_1stWon_x          486 non-null    float64
 33  w_2ndWon_x          486 non-null    float64
 34  w_SvGms             486 non-null    float64
 35  w_bpSaved           486 non-null    float64
 36  w_bpFaced           486 non-null    float64
 37  l_ace               2092 non-null   float64
 38  l_df                486 non-null    float64
 39  l_svpt              486 non-null    float64
 40  l_1stIn             2092 non-null   float64
 41  l_1stWon            2092 non-null   float64
 42  l_2ndWon            2092 non-null   float64
 43  l_SvGms             486 non-null    float64
 44  l_bpSaved           486 non-null    float64
 45  l_bpFaced           486 non-null    float64
 46  winner_rank         486 non-null    float64
 47  winner_rank_points  486 non-null    float64
 48  loser_rank          485 non-null    float64
 49  loser_rank_points   485 non-null    float64
 50  match_id            2092 non-null   object
 51  l_winners_fh        2092 non-null   int64
 52  l_winners_bh        2092 non-null   int64
 53  l_unforced_fh       2092 non-null   int64
 54  l_unforced_bh       2092 non-null   int64
 55  l_return_pts_faced  2092 non-null   int64
 56  l_return_pts_won    2092 non-null   int64
 57  w_1stIn_y           2092 non-null   int64
 58  w_1stWon_y          2092 non-null   int64
 59  w_2ndWon_y          2092 non-null   int64
 60  w_ace_y             2092 non-null   int64
 61  w_winners_fh        2092 non-null   int64
 62  w_winners_bh        2092 non-null   int64
 63  w_unforced_fh       2092 non-null   int64
 64  w_unforced_bh       2092 non-null   int64
 65  w_return_pts_faced  2092 non-null   int64
 66  w_return_pts_won    2092 non-null   int64
dtypes: float64(34), int64(16), object(17)
memory usage: 1.1+ MB

In [11]:
temp_data = data_merge_all.dropna(subset=['l_bpSaved'])
temp_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 486 entries, 10 to 2089
Data columns (total 67 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          486 non-null    float64
 1   tourney_id          486 non-null    object
 2   tourney_name        486 non-null    object
 3   surface             486 non-null    object
 4   draw_size           486 non-null    float64
 5   tourney_level       486 non-null    object
 6   tourney_date        486 non-null    float64
 7   match_num           486 non-null    float64
 8   winner_id           486 non-null    float64
 9   winner_seed         318 non-null    object
 10  winner_entry        56 non-null     object
 11  winner_name         486 non-null    object
 12  winner_hand         486 non-null    object
 13  winner_ht           485 non-null    float64
 14  winner_ioc          486 non-null    object
 15  winner_age          486 non-null    float64
 16  loser_id            486 non-null    float64
 17  loser_seed          276 non-null    object
 18  loser_entry         59 non-null     object
 19  loser_name          486 non-null    object
 20  loser_hand          486 non-null    object
 21  loser_ht            483 non-null    float64
 22  loser_ioc           486 non-null    object
 23  loser_age           486 non-null    float64
 24  score               486 non-null    object
 25  best_of             486 non-null    float64
 26  round               486 non-null    object
 27  minutes             470 non-null    float64
 28  w_ace_x             486 non-null    float64
 29  w_df                486 non-null    float64
 30  w_svpt              486 non-null    float64
 31  w_1stIn_x           486 non-null    float64
 32  w_1stWon_x          486 non-null    float64
 33  w_2ndWon_x          486 non-null    float64
 34  w_SvGms             486 non-null    float64
 35  w_bpSaved           486 non-null    float64
 36  w_bpFaced           486 non-null    float64
 37  l_ace               486 non-null    float64
 38  l_df                486 non-null    float64
 39  l_svpt              486 non-null    float64
 40  l_1stIn             486 non-null    float64
 41  l_1stWon            486 non-null    float64
 42  l_2ndWon            486 non-null    float64
 43  l_SvGms             486 non-null    float64
 44  l_bpSaved           486 non-null    float64
 45  l_bpFaced           486 non-null    float64
 46  winner_rank         486 non-null    float64
 47  winner_rank_points  486 non-null    float64
 48  loser_rank          485 non-null    float64
 49  loser_rank_points   485 non-null    float64
 50  match_id            486 non-null    object
 51  l_winners_fh        486 non-null    int64
 52  l_winners_bh        486 non-null    int64
 53  l_unforced_fh       486 non-null    int64
 54  l_unforced_bh       486 non-null    int64
 55  l_return_pts_faced  486 non-null    int64
 56  l_return_pts_won    486 non-null    int64
 57  w_1stIn_y           486 non-null    int64
 58  w_1stWon_y          486 non-null    int64
 59  w_2ndWon_y          486 non-null    int64
 60  w_ace_y             486 non-null    int64
 61  w_winners_fh        486 non-null    int64
 62  w_winners_bh        486 non-null    int64
 63  w_unforced_fh       486 non-null    int64
 64  w_unforced_bh       486 non-null    int64
 65  w_return_pts_faced  486 non-null    int64
 66  w_return_pts_won    486 non-null    int64
dtypes: float64(34), int64(16), object(17)
memory usage: 258.2+ KB

In [12]:
temp_data.reset_index(inplace=True)

In [13]:
temp_data

,index,Unnamed: 0,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,...,w_1stIn_y,w_1stWon_y,w_2ndWon_y,w_ace_y,w_winners_fh,w_winners_bh,w_unforced_fh,w_unforced_bh,w_return_pts_faced,w_return_pts_won
0,10,7324.0,2007-352,Paris Masters,Hard,48.0,M,20071028.0,47.0,103900.0,...,24,21,13,5,15,4,3,11,47,23
1,11,9141.0,2007-605,Masters Cup,Hard,8.0,F,20071112.0,5.0,104755.0,...,34,27,11,2,14,9,4,7,47,26
2,13,11748.0,2008-520,Roland Garros,Clay,128.0,G,20080525.0,127.0,104745.0,...,45,32,10,0,7,13,6,8,77,46
3,15,11033.0,2008-421,Canada Masters,Hard,56.0,M,20080721.0,55.0,104745.0,...,33,26,12,2,11,1,7,7,51,23
4,34,17728.0,2010-540,Wimbledon,Grass,128.0,G,20100621.0,127.0,104745.0,...,62,48,18,5,20,3,13,14,81,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,2073,50957.0,2022-0500,Halle,Grass,32.0,A,20220613.0,294.0,106401.0,...,32,29,9,13,16,7,6,7,57,24
482,2080,50954.0,2022-0500,Halle,Grass,32.0,A,20220613.0,297.0,106421.0,...,46,38,6,8,12,7,10,13,56,23
483,2084,51126.0,2022-540,Wimbledon,Grass,128.0,G,20220627.0,159.0,122298.0,...,35,32,23,10,23,5,7,5,74,34
484,2086,51174.0,2022-540,Wimbledon,Grass,128.0,G,20220627.0,207.0,106401.0,...,100,81,21,14,28,13,31,13,158,52
485,2089,51217.0,2022-0316,Bastad,Clay,32.0,A,20220711.0,275.0,106233.0,...,69,45,14,7,12,12,27,14,89,40

In [23]:
winner_player2 = np.zeros(temp_data.shape[0]) # second player wins so label=0
temp_data['label'] = winner_player2
temp_data

<ipython-input-23-4217fc0030f7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_data['label'] = winner_player2

,index,Unnamed: 0,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,...,w_1stWon_y,w_2ndWon_y,w_ace_y,w_winners_fh,w_winners_bh,w_unforced_fh,w_unforced_bh,w_return_pts_faced,w_return_pts_won,label
0,10,7324.0,2007-352,Paris Masters,Hard,48.0,M,20071028.0,47.0,103900.0,...,21,13,5,15,4,3,11,47,23,0.0
1,11,9141.0,2007-605,Masters Cup,Hard,8.0,F,20071112.0,5.0,104755.0,...,27,11,2,14,9,4,7,47,26,0.0
2,13,11748.0,2008-520,Roland Garros,Clay,128.0,G,20080525.0,127.0,104745.0,...,32,10,0,7,13,6,8,77,46,0.0
3,15,11033.0,2008-421,Canada Masters,Hard,56.0,M,20080721.0,55.0,104745.0,...,26,12,2,11,1,7,7,51,23,0.0
4,34,17728.0,2010-540,Wimbledon,Grass,128.0,G,20100621.0,127.0,104745.0,...,48,18,5,20,3,13,14,81,27,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,2073,50957.0,2022-0500,Halle,Grass,32.0,A,20220613.0,294.0,106401.0,...,29,9,13,16,7,6,7,57,24,0.0
482,2080,50954.0,2022-0500,Halle,Grass,32.0,A,20220613.0,297.0,106421.0,...,38,6,8,12,7,10,13,56,23,0.0
483,2084,51126.0,2022-540,Wimbledon,Grass,128.0,G,20220627.0,159.0,122298.0,...,32,23,10,23,5,7,5,74,34,0.0
484,2086,51174.0,2022-540,Wimbledon,Grass,128.0,G,20220627.0,207.0,106401.0,...,81,21,14,28,13,31,13,158,52,0.0
485,2089,51217.0,2022-0316,Bastad,Clay,32.0,A,20220711.0,275.0,106233.0,...,45,14,7,12,12,27,14,89,40,0.0

In [24]:
temp_data.to_csv('data/second-ATP.csv')

In [25]:
first_ATP = pd.read_csv('data/first-ATP.csv')

In [26]:
data = pd.concat([temp_data ,first_ATP], ignore_index = True)

In [27]:
data.duplicated().sum()

0

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 70 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               998 non-null    int64
 1   Unnamed: 0          998 non-null    float64
 2   tourney_id          998 non-null    object
 3   tourney_name        998 non-null    object
 4   surface             998 non-null    object
 5   draw_size           998 non-null    float64
 6   tourney_level       998 non-null    object
 7   tourney_date        998 non-null    float64
 8   match_num           998 non-null    float64
 9   winner_id           998 non-null    float64
 10  winner_seed         682 non-null    object
 11  winner_entry        101 non-null    object
 12  winner_name         998 non-null    object
 13  winner_hand         998 non-null    object
 14  winner_ht           997 non-null    float64
 15  winner_ioc          998 non-null    object
 16  winner_age          998 non-null    float64
 17  loser_id            998 non-null    float64
 18  loser_seed          539 non-null    object
 19  loser_entry         125 non-null    object
 20  loser_name          998 non-null    object
 21  loser_hand          998 non-null    object
 22  loser_ht            992 non-null    float64
 23  loser_ioc           998 non-null    object
 24  loser_age           998 non-null    float64
 25  score               998 non-null    object
 26  best_of             998 non-null    float64
 27  round               998 non-null    object
 28  minutes             949 non-null    float64
 29  w_ace_x             998 non-null    float64
 30  w_df                998 non-null    float64
 31  w_svpt              998 non-null    float64
 32  w_1stIn_x           998 non-null    float64
 33  w_1stWon_x          998 non-null    float64
 34  w_2ndWon_x          998 non-null    float64
 35  w_SvGms             998 non-null    float64
 36  w_bpSaved           998 non-null    float64
 37  w_bpFaced           998 non-null    float64
 38  l_ace               998 non-null    float64
 39  l_df                998 non-null    float64
 40  l_svpt              998 non-null    float64
 41  l_1stIn             998 non-null    float64
 42  l_1stWon            998 non-null    float64
 43  l_2ndWon            998 non-null    float64
 44  l_SvGms             998 non-null    float64
 45  l_bpSaved           998 non-null    float64
 46  l_bpFaced           998 non-null    float64
 47  winner_rank         998 non-null    float64
 48  winner_rank_points  998 non-null    float64
 49  loser_rank          997 non-null    float64
 50  loser_rank_points   997 non-null    float64
 51  match_id            998 non-null    object
 52  l_winners_fh        998 non-null    int64
 53  l_winners_bh        998 non-null    int64
 54  l_unforced_fh       998 non-null    int64
 55  l_unforced_bh       998 non-null    int64
 56  l_return_pts_faced  998 non-null    int64
 57  l_return_pts_won    998 non-null    int64
 58  w_1stIn_y           998 non-null    int64
 59  w_1stWon_y          998 non-null    int64
 60  w_2ndWon_y          998 non-null    int64
 61  w_ace_y             998 non-null    int64
 62  w_winners_fh        998 non-null    int64
 63  w_winners_bh        998 non-null    int64
 64  w_unforced_fh       998 non-null    int64
 65  w_unforced_bh       998 non-null    int64
 66  w_return_pts_faced  998 non-null    int64
 67  w_return_pts_won    998 non-null    int64
 68  label               998 non-null    float64
 69  Unnamed: 0.1        512 non-null    float64
dtypes: float64(36), int64(17), object(17)
memory usage: 545.9+ KB

In [ ]:
data.drop(['w_2ndWon_y','w_1stWon_y','w_1stIn_y','Unnamed: 0.1','Unnamed: 0','index',])

In [29]:
data.to_csv('data/final-ATP.csv')

In [30]:
final_df = pd.read_csv('data/final-ATP.csv') 
final_df

,Unnamed: 0,index,Unnamed: 0.1,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,...,w_2ndWon_y,w_ace_y,w_winners_fh,w_winners_bh,w_unforced_fh,w_unforced_bh,w_return_pts_faced,w_return_pts_won,label,Unnamed: 0.1.1
0,0,10,7324.0,2007-352,Paris Masters,Hard,48.0,M,20071028.0,47.0,...,13,5,15,4,3,11,47,23,0.0,NaN
1,1,11,9141.0,2007-605,Masters Cup,Hard,8.0,F,20071112.0,5.0,...,11,2,14,9,4,7,47,26,0.0,NaN
2,2,13,11748.0,2008-520,Roland Garros,Clay,128.0,G,20080525.0,127.0,...,10,0,7,13,6,8,77,46,0.0,NaN
3,3,15,11033.0,2008-421,Canada Masters,Hard,56.0,M,20080721.0,55.0,...,12,2,11,1,7,7,51,23,0.0,NaN
4,4,34,17728.0,2010-540,Wimbledon,Grass,128.0,G,20100621.0,127.0,...,18,5,20,3,13,14,81,27,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,993,2081,507.0,2022-0321,Stuttgart,Grass,32.0,A,20220606.0,290.0,...,18,21,12,3,10,5,101,34,1.0,50934.0
994,994,2085,508.0,2022-540,Wimbledon,Grass,128.0,G,20220627.0,212.0,...,25,7,14,7,17,8,124,56,1.0,51179.0
995,995,2088,509.0,2022-0315,Newport,Grass,32.0,A,20220711.0,278.0,...,7,5,2,2,2,6,38,26,1.0,51241.0
996,996,2090,510.0,2022-540,Wimbledon,Grass,128.0,G,20220627.0,222.0,...,14,17,11,4,21,17,88,32,1.0,51189.0
997,997,2091,511.0,2022-0315,Newport,Grass,32.0,A,20220711.0,290.0,...,16,8,10,7,11,7,80,44,1.0,51231.0

755