In [ ]:
# import
import pandas as pd
import numpy as np

:

In [3]:
f = pd.read_csv('../data/charting-m-points.csv' , encoding = "ISO-8859-1")
# f2 = pd.read_csv('../data/charting-m-stats-Overview.csv')

f.head()

/opt/conda/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (8,9,29) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,match_id,Pt,Set1,Set2,Gm1,Gm2,Pts,Gm#,TbSet,TB?,...,2ndIn,isAce,isUnret,isRallyWinner,isForced,isUnforced,isDouble,PtWinner,isSvrWinner,rallyCount
0,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,1,0,0,0.0,0.0,0-0,1 (1),1,0,...,NaN,False,False,False,False,False,False,1,1,1
1,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,2,0,0,0.0,0.0,15-0,1 (2),1,0,...,NaN,False,False,False,False,False,False,1,1,1
2,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,3,0,0,0.0,0.0,30-0,1 (3),1,0,...,1.0,False,False,False,True,False,False,1,1,1
3,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,4,0,0,0.0,0.0,40-0,1 (4),1,0,...,NaN,True,False,False,False,False,False,1,1,1
4,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,5,0,0,1.0,0.0,0-0,2 (1),1,0,...,1.0,False,False,False,False,True,False,1,0,2

I have two data sources as referenced on the README file. The first Reposotry contains basic information about every match. The second one has detailed information for selected matches. In this section, I will join the data from the first Repository and the second Repository. This will enable me to have an in depth analysis on the players and more accurate results on the ML part. 
The steps for this is as follows : 
1- cbind the target fetures from the second Repo into one Dataset
2- cbind the dataset of the extra fetures with the first Repo dataset 
3- Clean the final dataset

In [18]:
p2 = pd.read_csv('../data/charting-m-stats-Overview.csv')
p2

,match_id,player,set,serve_pts,aces,dfs,first_in,first_won,second_in,second_won,bk_pts,bp_saved,return_pts,return_pts_won,winners,winners_fh,winners_bh,unforced,unforced_fh,unforced_bh
0,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,1,Total,69,2,1,32,25,37,21,5,4,63,36,28,10,16,16,6,9
1,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,2,Total,63,2,2,41,20,22,7,12,4,69,23,14,8,4,26,15,9
2,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,1,1,26,2,0,15,10,11,6,2,1,18,13,10,3,5,6,2,4
3,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,2,1,18,0,0,11,3,7,2,3,0,26,10,4,2,2,10,7,3
4,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,1,2,24,0,0,10,9,14,8,1,1,26,10,9,3,6,6,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19735,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,2,1,40,3,0,22,13,18,10,7,6,27,12,10,4,3,13,6,7
19736,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,1,2,30,3,2,22,15,8,4,4,3,23,15,9,4,2,9,3,4
19737,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,2,2,23,2,0,14,6,9,2,4,1,30,11,6,1,3,13,8,5
19738,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,1,3,30,2,2,13,10,17,7,3,2,17,12,9,4,3,5,1,2
19739,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,2,3,17,0,1,9,3,8,2,4,1,30,13,7,5,2,13,7,5

In [62]:
overview_p2 = pd.read_csv('../data/charting-m-stats-Overview.csv')
# overview_p2 = overview_p2.loc[overview_p2['set'] == 'Total', :]
overview_p2

,match_id,player,set,serve_pts,aces,dfs,first_in,first_won,second_in,second_won,bk_pts,bp_saved,return_pts,return_pts_won,winners,winners_fh,winners_bh,unforced,unforced_fh,unforced_bh
0,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,1,Total,69,2,1,32,25,37,21,5,4,63,36,28,10,16,16,6,9
1,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,2,Total,63,2,2,41,20,22,7,12,4,69,23,14,8,4,26,15,9
8,19780125-M-Pepsi_Grand_Slam-SF-Brian_Gottfried...,1,Total,55,0,1,32,21,23,9,9,5,49,14,11,7,4,31,9,21
9,19780125-M-Pepsi_Grand_Slam-SF-Brian_Gottfried...,2,Total,49,0,2,31,25,18,10,1,0,55,25,15,8,7,21,7,12
14,19800705-M-Wimbledon-F-John_Mcenroe-Bjorn_Borg,1,Total,180,12,3,111,75,69,44,14,10,196,65,69,28,29,102,29,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19717,20220712-M-Bastad-R32-Emil_Ruusuvuori-Dominic_...,2,Total,98,7,3,69,45,29,14,12,8,89,40,31,12,12,44,27,14
19724,20220706-M-Wimbledon-QF-Nick_Kyrgios-Cristian_...,1,Total,114,17,4,81,59,33,14,9,8,88,32,62,11,4,42,21,17
19725,20220706-M-Wimbledon-QF-Nick_Kyrgios-Cristian_...,2,Total,88,2,5,63,43,25,13,6,3,114,41,44,16,8,33,15,13
19732,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,1,Total,87,8,5,50,35,37,16,11,7,80,44,25,10,7,23,11,7
19733,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,2,Total,80,5,1,45,22,35,14,15,8,87,36,23,10,8,39,21,17

Merge the other datasets from the same Repo

In [63]:
df2 = pd.read_csv('../data/charting-m-stats-ReturnDepth.csv')
#Return- w_ReturenSh,w_ReturenD,w_ReturenVD
# Returen Outcome- w_ReturenWon
col = df2.columns.tolist()
df2 = df2.rename_axis([str(x) for x in range(8)]).reset_index()
df2 = df2.set_axis(col+[str(x) for x in range(8)], axis=1)
df2.drop([str(x) for x in range(8)], axis=1, inplace=True)
df2[['tourney_date', 'sm', 'tourney_name', 'sm2', 'player1', 'player2']
    ] = df2['match_id'].str.split('-', 6, expand=True)
# df2.loc[:,['player1','player2']]=df2.loc[:,['player1','player2']].applymap(lambda x: x.replace('_',' ') ) #for multiple columns
df2 = df2.loc[df2['row'] == 'Total', :]
# So I want to change the value of the column player from 1 to the value of the name in column player1
# 1,16,17 are the index
# for i in range(len(df2)) :
#     df2.iloc[i,1] = np.where(df2.iloc[i,1] == 1, df2.iloc[i,16], df2.iloc[i,17])
df2.drop(['player1', 'player2', 'sm', 'sm2', 'tourney_name',
         'tourney_date', 'unforced'], axis=1, inplace=True)
df2.rename(columns={'row': 'set'}, inplace=True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5198 entries, 0 to 93017
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   match_id       5198 non-null   object
 1   player         5198 non-null   int64
 2   set            5198 non-null   object
 3   returnable     5198 non-null   int64
 4   shallow        5198 non-null   int64
 5   deep           5198 non-null   int64
 6   very_deep      5198 non-null   int64
 7   err_net        5198 non-null   int64
 8   err_deep       5198 non-null   int64
 9   err_wide       5198 non-null   int64
 10  err_wide_deep  5198 non-null   int64
dtypes: int64(9), object(2)
memory usage: 487.3+ KB

In [64]:
df4 = pd.read_csv('../data/charting-m-stats-ShotDirection.csv')
col = df4.columns.tolist()
df4 = df4.rename_axis([str(x) for x in range(12)]).reset_index()
df4 = df4.set_axis(col+[str(x) for x in range(12)], axis=1)
df4.drop([str(x) for x in range(12)], axis=1, inplace=True)
df4[['tourney_date', 'sm', 'tourney_name', 'sm2', 'player1', 'player2']
    ] = df4['match_id'].str.split('-', 6, expand=True)
# df4.loc[:,['player1','player2']]=df4.loc[:,['player1','player2']].applymap(lambda x: x.replace('_',' ') ) #for multiple columns
df4 = df4.loc[df4['row'] == 'Total', :]
# So I want to change the value of the column player from 1 to the value of the name in column player1
# 1,16,17 are the index
# for i in range(len(df4)) :
#     df4.iloc[i,1] = np.where(df4.iloc[i,1] == 1, df4.iloc[i,12], df4.iloc[i,13])
df4.rename(columns={'row': 'set'}, inplace=True)

df4.drop(['player1', 'player2', 'sm', 'sm2', 'tourney_name',
         'tourney_date'], axis=1, inplace=True)
df4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5201 entries, 0 to 20610
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   match_id       5201 non-null   object
 1   player         5201 non-null   int64
 2   set            5201 non-null   object
 3   crosscourt     5201 non-null   int64
 4   down_middle    5201 non-null   int64
 5   down_the_line  5201 non-null   int64
 6   inside_out     5201 non-null   int64
 7   inside_in      5201 non-null   int64
dtypes: int64(6), object(2)
memory usage: 365.7+ KB

In [65]:

overview_p2 = pd.merge(overview_p2,
                       df2,
                       on=['match_id', 'set', 'player'],
                       how="right")
overview_p2 = pd.merge(overview_p2,
                       df4,
                       on=['match_id', 'set', 'player'],
                       how="right")

overview_p2.drop_duplicates(inplace=True)
overview_p2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5193 entries, 0 to 5248
Data columns (total 33 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   match_id        5193 non-null   object
 1   player          5193 non-null   int64
 2   set             5193 non-null   object
 3   serve_pts       5186 non-null   float64
 4   aces            5186 non-null   float64
 5   dfs             5186 non-null   float64
 6   first_in        5186 non-null   float64
 7   first_won       5186 non-null   float64
 8   second_in       5186 non-null   float64
 9   second_won      5186 non-null   float64
 10  bk_pts          5186 non-null   float64
 11  bp_saved        5186 non-null   float64
 12  return_pts      5186 non-null   float64
 13  return_pts_won  5186 non-null   float64
 14  winners         5186 non-null   float64
 15  winners_fh      5186 non-null   float64
 16  winners_bh      5186 non-null   float64
 17  unforced        5186 non-null   float64
 18  unforced_fh     5186 non-null   float64
 19  unforced_bh     5186 non-null   float64
 20  returnable      5186 non-null   float64
 21  shallow         5186 non-null   float64
 22  deep            5186 non-null   float64
 23  very_deep       5186 non-null   float64
 24  err_net         5186 non-null   float64
 25  err_deep        5186 non-null   float64
 26  err_wide        5186 non-null   float64
 27  err_wide_deep   5186 non-null   float64
 28  crosscourt      5193 non-null   int64
 29  down_middle     5193 non-null   int64
 30  down_the_line   5193 non-null   int64
 31  inside_out      5193 non-null   int64
 32  inside_in       5193 non-null   int64
dtypes: float64(25), int64(6), object(2)
memory usage: 1.3+ MB

In [66]:
print(overview_p2.columns.tolist())

['match_id', 'player', 'set', 'serve_pts', 'aces', 'dfs', 'first_in', 'first_won', 'second_in', 'second_won', 'bk_pts', 'bp_saved', 'return_pts', 'return_pts_won', 'winners', 'winners_fh', 'winners_bh', 'unforced', 'unforced_fh', 'unforced_bh', 'returnable', 'shallow', 'deep', 'very_deep', 'err_net', 'err_deep', 'err_wide', 'err_wide_deep', 'crosscourt', 'down_middle', 'down_the_line', 'inside_out', 'inside_in']

In [67]:
overview_p1 = overview_p2.copy()
overview_p2_w = overview_p2.copy()
overview_p1_w = overview_p2.copy()
overview_p2

,match_id,player,set,serve_pts,aces,dfs,first_in,first_won,second_in,second_won,...,very_deep,err_net,err_deep,err_wide,err_wide_deep,crosscourt,down_middle,down_the_line,inside_out,inside_in
0,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,1,Total,69.0,2.0,1.0,32.0,25.0,37.0,21.0,...,12.0,0.0,1.0,0.0,0.0,87,43,19,22,0
1,19751219-M-Davis_Cup_World_Group_F-RR-Bjorn_Bo...,2,Total,63.0,2.0,2.0,41.0,20.0,22.0,7.0,...,10.0,1.0,0.0,2.0,0.0,79,52,17,26,2
2,19780125-M-Pepsi_Grand_Slam-SF-Brian_Gottfried...,1,Total,55.0,0.0,1.0,32.0,21.0,23.0,9.0,...,16.0,3.0,0.0,0.0,0.0,88,33,20,13,0
3,19780125-M-Pepsi_Grand_Slam-SF-Brian_Gottfried...,2,Total,49.0,0.0,2.0,31.0,25.0,18.0,10.0,...,9.0,0.0,1.0,0.0,0.0,132,45,19,10,2
4,19800705-M-Wimbledon-F-John_Mcenroe-Bjorn_Borg,1,Total,180.0,12.0,3.0,111.0,75.0,69.0,44.0,...,25.0,20.0,11.0,7.0,0.0,43,25,40,17,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5244,20220712-M-Bastad-R32-Emil_Ruusuvuori-Dominic_...,2,Total,98.0,7.0,3.0,69.0,45.0,29.0,14.0,...,18.0,0.0,3.0,0.0,0.0,141,102,25,46,3
5245,20220706-M-Wimbledon-QF-Nick_Kyrgios-Cristian_...,1,Total,114.0,17.0,4.0,81.0,59.0,33.0,14.0,...,0.0,0.0,3.0,0.0,0.0,44,99,14,34,0
5246,20220706-M-Wimbledon-QF-Nick_Kyrgios-Cristian_...,2,Total,88.0,2.0,5.0,63.0,43.0,25.0,13.0,...,0.0,0.0,0.0,0.0,0.0,66,94,4,27,1
5247,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,1,Total,87.0,8.0,5.0,50.0,35.0,37.0,16.0,...,15.0,0.0,0.0,0.0,0.0,131,60,35,39,7
5248,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,2,Total,80.0,5.0,1.0,45.0,22.0,35.0,14.0,...,22.0,1.0,0.0,0.0,0.0,118,45,31,23,0

In [68]:
first_repo_data = pd.read_csv('../data/atp_matches_2005-2022.csv')
first_repo_data.head()

/opt/conda/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (9,17) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unnamed: 0,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,0,2005-1536,Madrid Masters,Hard,48,M,20051017,1,103812,NaN,...,27.0,20.0,6.0,8.0,2.0,5.0,42.0,827.0,63.0,621.0
1,1,2005-1536,Madrid Masters,Hard,48,M,20051017,2,102845,NaN,...,24.0,16.0,9.0,7.0,5.0,9.0,33.0,1005.0,41.0,836.0
2,2,2005-1536,Madrid Masters,Hard,48,M,20051017,3,102450,NaN,...,22.0,15.0,20.0,9.0,1.0,4.0,26.0,1120.0,28.0,1115.0
3,3,2005-1536,Madrid Masters,Hard,48,M,20051017,4,104076,NaN,...,32.0,22.0,25.0,12.0,4.0,8.0,55.0,678.0,29.0,1090.0
4,4,2005-1536,Madrid Masters,Hard,48,M,20051017,5,103971,NaN,...,21.0,13.0,6.0,6.0,2.0,5.0,45.0,771.0,30.0,1070.0

One important thing here is that as we see the players information in the second repo are on diffrent rows whereas on the first they are in one row. Another problem is that in the first repo we have the winner info and the loser info denoted by 
w & l. Therefore we have to match player 1 & 2 names into winner_name and loser_name and the same for the rest. Since sometime player1 is the winner and sometime player2 is the winner I solve this issue by creating two datasets. 
The first one is where the first player is the winner and add a new column 'Label' with a value of 1. The second dataset if player2 is the winner with a label of value 0

The columns that I will add from the second repo datasets: 
The overview dataset :  ['winners_fh','winners_bh','unforced_fh','unforced_bh','return_pts','return_pts_won']

The data cleaning proccess for the second repo datasets is the same for each dataset : 
split the match_id to get the players names and rename other fetures to merge the datasets based on the names and the common fetures such as aces (This is because some players can play againest each other multiple times)

In [69]:
first_repo_data.columns.tolist()

['Unnamed: 0',
 'tourney_id',
 'tourney_name',
 'surface',
 'draw_size',
 'tourney_level',
 'tourney_date',
 'match_num',
 'winner_id',
 'winner_seed',
 'winner_entry',
 'winner_name',
 'winner_hand',
 'winner_ht',
 'winner_ioc',
 'winner_age',
 'loser_id',
 'loser_seed',
 'loser_entry',
 'loser_name',
 'loser_hand',
 'loser_ht',
 'loser_ioc',
 'loser_age',
 'score',
 'best_of',
 'round',
 'minutes',
 'w_ace',
 'w_df',
 'w_svpt',
 'w_1stIn',
 'w_1stWon',
 'w_2ndWon',
 'w_SvGms',
 'w_bpSaved',
 'w_bpFaced',
 'l_ace',
 'l_df',
 'l_svpt',
 'l_1stIn',
 'l_1stWon',
 'l_2ndWon',
 'l_SvGms',
 'l_bpSaved',
 'l_bpFaced',
 'winner_rank',
 'winner_rank_points',
 'loser_rank',
 'loser_rank_points']

In [70]:
overview_p2[['tourney_date', 'sm', 'tourney_name', 'sm2', 'player1',
             'player2']] = overview_p2['match_id'].str.split('-', 6, expand=True)
overview_p2['tourney_date'] = overview_p2['tourney_date'].apply(
    lambda x: int(x))
overview_p2 = overview_p2.loc[overview_p2['tourney_date'] > 20000000, :]
overview_p2 = overview_p2[(overview_p2['player'] == 2)]
overview_p2['l_1stIn'] = overview_p2['first_in']
overview_p2['l_1stWon'] = overview_p2['first_won']
overview_p2['l_2ndWon'] = overview_p2['second_won']
overview_p2['l_ace'] = overview_p2['aces']
overview_p2['l_winners_fh'] = overview_p2['winners_fh']
overview_p2['l_winners_bh'] = overview_p2['winners_bh']
overview_p2['l_unforced_fh'] = overview_p2['unforced_fh']
overview_p2['l_unforced_bh'] = overview_p2['unforced_bh']
overview_p2['l_return_pts_faced'] = overview_p2['return_pts']
overview_p2['l_return_pts_won'] = overview_p2['return_pts_won']
overview_p2['l_return_depth_very_deep'] = overview_p2['very_deep']
overview_p2['l_return_depth_shallow'] = overview_p2['shallow']
overview_p2['l_return_depth_deep'] = overview_p2['deep']
overview_p2['l_return_depth_err_net'] = overview_p2['err_net']
overview_p2['l_return_depth_err_deep'] = overview_p2['err_deep']
overview_p2['l_return_depth_err_wide'] = overview_p2['err_wide']
overview_p2['l_return_depth_wide_deep'] = overview_p2['err_wide_deep']
overview_p2['l_shot_Direction_crosscourt'] = overview_p2['crosscourt']
overview_p2['l_shot_Direction_down_middle'] = overview_p2['down_middle']
overview_p2['l_shot_Direction_down_the_line'] = overview_p2['down_the_line']
overview_p2['l_shot_Direction_inside_out'] = overview_p2['inside_out']
overview_p2['l_shot_Direction_inside_in'] = overview_p2['inside_in']
overview_p2.drop(overview_p2.columns.to_list()[1:37], axis=1, inplace=True)
overview_p2.rename(columns={'player1': 'winner_name',
                   'player2': 'loser_name'}, inplace=True)
overview_p2.loc[:, ['winner_name', 'loser_name']] = overview_p2.loc[:, [
    'winner_name', 'loser_name']].applymap(lambda x: x.replace('_', ' '))  # for multiple columns
print(overview_p2.columns.tolist())
print(overview_p2.info())

['match_id', 'winner_name', 'loser_name', 'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_ace', 'l_winners_fh', 'l_winners_bh', 'l_unforced_fh', 'l_unforced_bh', 'l_return_pts_faced', 'l_return_pts_won', 'l_return_depth_very_deep', 'l_return_depth_shallow', 'l_return_depth_deep', 'l_return_depth_err_net', 'l_return_depth_err_deep', 'l_return_depth_err_wide', 'l_return_depth_wide_deep', 'l_shot_Direction_crosscourt', 'l_shot_Direction_down_middle', 'l_shot_Direction_down_the_line', 'l_shot_Direction_inside_out', 'l_shot_Direction_inside_in']
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2257 entries, 99 to 5248
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   match_id                        2257 non-null   object
 1   winner_name                     2257 non-null   object
 2   loser_name                      2257 non-null   object
 3   l_1stIn                         2254 non-null   float64
 4   l_1stWon                        2254 non-null   float64
 5   l_2ndWon                        2254 non-null   float64
 6   l_ace                           2254 non-null   float64
 7   l_winners_fh                    2254 non-null   float64
 8   l_winners_bh                    2254 non-null   float64
 9   l_unforced_fh                   2254 non-null   float64
 10  l_unforced_bh                   2254 non-null   float64
 11  l_return_pts_faced              2254 non-null   float64
 12  l_return_pts_won                2254 non-null   float64
 13  l_return_depth_very_deep        2254 non-null   float64
 14  l_return_depth_shallow          2254 non-null   float64
 15  l_return_depth_deep             2254 non-null   float64
 16  l_return_depth_err_net          2254 non-null   float64
 17  l_return_depth_err_deep         2254 non-null   float64
 18  l_return_depth_err_wide         2254 non-null   float64
 19  l_return_depth_wide_deep        2254 non-null   float64
 20  l_shot_Direction_crosscourt     2257 non-null   int64
 21  l_shot_Direction_down_middle    2257 non-null   int64
 22  l_shot_Direction_down_the_line  2257 non-null   int64
 23  l_shot_Direction_inside_out     2257 non-null   int64
 24  l_shot_Direction_inside_in      2257 non-null   int64
dtypes: float64(17), int64(5), object(3)
memory usage: 458.5+ KB
None

In [71]:
overview_p1[['tourney_date', 'sm', 'tourney_name', 'sm2', 'player1',
             'player2']] = overview_p1['match_id'].str.split('-', 6, expand=True)
# df.rename(columns = {'first_in':'l_1stIn', 'first_won':'l_1stWon','second_won' : 'l_2ndWon', 'aces' : 'l_ace'}, inplace = True)
overview_p1['tourney_date'] = overview_p1['tourney_date'].apply(
    lambda x: int(x))
overview_p1 = overview_p1.loc[overview_p1['tourney_date'] > 20000000, :]
overview_p1 = overview_p1[(overview_p1['set'] == 'Total')
                          & (overview_p1['player'] == 1)]
# df[df['l_1stIn' , 'l_1stWon','l_2ndWon' , 'l_ace']] = df['first_in', 'first_won','second_won' , 'aces' ]
overview_p1['w_1stIn'] = overview_p1['first_in']
overview_p1['w_1stWon'] = overview_p1['first_won']
overview_p1['w_2ndWon'] = overview_p1['second_won']
overview_p1['w_ace'] = overview_p1['aces']
overview_p1['w_winners_fh'] = overview_p1['winners_fh']
overview_p1['w_winners_bh'] = overview_p1['winners_bh']
overview_p1['w_unforced_fh'] = overview_p1['unforced_fh']
overview_p1['w_unforced_bh'] = overview_p1['unforced_bh']
overview_p1['w_return_pts_faced'] = overview_p1['return_pts']
overview_p1['w_return_pts_won'] = overview_p1['return_pts_won']
overview_p1['w_return_depth_very_deep'] = overview_p1['very_deep']
overview_p1['w_return_depth_shallow'] = overview_p1['shallow']
overview_p1['w_return_depth_deep'] = overview_p1['deep']
overview_p1['w_return_depth_err_net'] = overview_p1['err_net']
overview_p1['w_return_depth_err_deep'] = overview_p1['err_deep']
overview_p1['w_return_depth_err_wide'] = overview_p1['err_wide']
overview_p1['w_return_depth_wide_deep'] = overview_p1['err_wide_deep']
overview_p1['w_shot_Direction_crosscourt'] = overview_p1['crosscourt']
overview_p1['w_shot_Direction_down_middle'] = overview_p1['down_middle']
overview_p1['w_shot_Direction_down_the_line'] = overview_p1['down_the_line']
overview_p1['w_shot_Direction_inside_out'] = overview_p1['inside_out']
overview_p1['w_shot_Direction_inside_in'] = overview_p1['inside_in']
overview_p1.drop(overview_p1.columns.to_list()[1:37], axis=1, inplace=True)
overview_p1.rename(columns={'player1': 'winner_name',
                   'player2': 'loser_name'}, inplace=True)
overview_p1.loc[:, ['winner_name', 'loser_name']] = overview_p1.loc[:, [
    'winner_name', 'loser_name']].applymap(lambda x: x.replace('_', ' '))  # for multiple columns
overview_p1
print(overview_p1.columns.tolist())
print(overview_p1.info())

['match_id', 'winner_name', 'loser_name', 'w_1stIn', 'w_1stWon', 'w_2ndWon', 'w_ace', 'w_winners_fh', 'w_winners_bh', 'w_unforced_fh', 'w_unforced_bh', 'w_return_pts_faced', 'w_return_pts_won', 'w_return_depth_very_deep', 'w_return_depth_shallow', 'w_return_depth_deep', 'w_return_depth_err_net', 'w_return_depth_err_deep', 'w_return_depth_err_wide', 'w_return_depth_wide_deep', 'w_shot_Direction_crosscourt', 'w_shot_Direction_down_middle', 'w_shot_Direction_down_the_line', 'w_shot_Direction_inside_out', 'w_shot_Direction_inside_in']
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2258 entries, 98 to 5247
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   match_id                        2258 non-null   object
 1   winner_name                     2258 non-null   object
 2   loser_name                      2258 non-null   object
 3   w_1stIn                         2254 non-null   float64
 4   w_1stWon                        2254 non-null   float64
 5   w_2ndWon                        2254 non-null   float64
 6   w_ace                           2254 non-null   float64
 7   w_winners_fh                    2254 non-null   float64
 8   w_winners_bh                    2254 non-null   float64
 9   w_unforced_fh                   2254 non-null   float64
 10  w_unforced_bh                   2254 non-null   float64
 11  w_return_pts_faced              2254 non-null   float64
 12  w_return_pts_won                2254 non-null   float64
 13  w_return_depth_very_deep        2254 non-null   float64
 14  w_return_depth_shallow          2254 non-null   float64
 15  w_return_depth_deep             2254 non-null   float64
 16  w_return_depth_err_net          2254 non-null   float64
 17  w_return_depth_err_deep         2254 non-null   float64
 18  w_return_depth_err_wide         2254 non-null   float64
 19  w_return_depth_wide_deep        2254 non-null   float64
 20  w_shot_Direction_crosscourt     2258 non-null   int64
 21  w_shot_Direction_down_middle    2258 non-null   int64
 22  w_shot_Direction_down_the_line  2258 non-null   int64
 23  w_shot_Direction_inside_out     2258 non-null   int64
 24  w_shot_Direction_inside_in      2258 non-null   int64
dtypes: float64(17), int64(5), object(3)
memory usage: 458.7+ KB
None

In [72]:
overview_clean = pd.merge(overview_p1,
                          overview_p2,
                          on=['winner_name', 'loser_name', 'match_id'],
                          how="outer")

player1_merged = pd.merge(first_repo_data,
                          overview_clean,
                          on=['l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_ace', 'winner_name',
                              'loser_name', 'w_1stIn', 'w_1stWon', 'w_2ndWon', 'w_ace'],
                          how="right")
print(player1_merged.info())
# player1_merged = player1_merged.dropna(subset=['l_bpSaved'])
player1_merged.reset_index(inplace=True)
# first player wins so label=1
winner_player1 = np.ones(player1_merged.shape[0])
player1_merged['label'] = winner_player1
# print(player1_merged.info())
# display(player1_merged.head())

player1_merged.to_csv('../data/first-ATP.csv')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2258 entries, 0 to 2257
Data columns (total 87 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      323 non-null    float64
 1   tourney_id                      323 non-null    object
 2   tourney_name                    323 non-null    object
 3   surface                         323 non-null    object
 4   draw_size                       323 non-null    float64
 5   tourney_level                   323 non-null    object
 6   tourney_date                    323 non-null    float64
 7   match_num                       323 non-null    float64
 8   winner_id                       323 non-null    float64
 9   winner_seed                     227 non-null    object
 10  winner_entry                    27 non-null     object
 11  winner_name                     2258 non-null   object
 12  winner_hand                     323 non-null    object
 13  winner_ht                       323 non-null    float64
 14  winner_ioc                      323 non-null    object
 15  winner_age                      323 non-null    float64
 16  loser_id                        323 non-null    float64
 17  loser_seed                      156 non-null    object
 18  loser_entry                     43 non-null     object
 19  loser_name                      2258 non-null   object
 20  loser_hand                      323 non-null    object
 21  loser_ht                        320 non-null    float64
 22  loser_ioc                       323 non-null    object
 23  loser_age                       323 non-null    float64
 24  score                           323 non-null    object
 25  best_of                         323 non-null    float64
 26  round                           323 non-null    object
 27  minutes                         304 non-null    float64
 28  w_ace                           2254 non-null   float64
 29  w_df                            322 non-null    float64
 30  w_svpt                          322 non-null    float64
 31  w_1stIn                         2254 non-null   float64
 32  w_1stWon                        2254 non-null   float64
 33  w_2ndWon                        2254 non-null   float64
 34  w_SvGms                         322 non-null    float64
 35  w_bpSaved                       322 non-null    float64
 36  w_bpFaced                       322 non-null    float64
 37  l_ace                           2254 non-null   float64
 38  l_df                            322 non-null    float64
 39  l_svpt                          322 non-null    float64
 40  l_1stIn                         2254 non-null   float64
 41  l_1stWon                        2254 non-null   float64
 42  l_2ndWon                        2254 non-null   float64
 43  l_SvGms                         322 non-null    float64
 44  l_bpSaved                       322 non-null    float64
 45  l_bpFaced                       322 non-null    float64
 46  winner_rank                     323 non-null    float64
 47  winner_rank_points              323 non-null    float64
 48  loser_rank                      323 non-null    float64
 49  loser_rank_points               323 non-null    float64
 50  match_id                        2258 non-null   object
 51  w_winners_fh                    2254 non-null   float64
 52  w_winners_bh                    2254 non-null   float64
 53  w_unforced_fh                   2254 non-null   float64
 54  w_unforced_bh                   2254 non-null   float64
 55  w_return_pts_faced              2254 non-null   float64
 56  w_return_pts_won                2254 non-null   float64
 57  w_return_depth_very_deep        2254 non-null   float64
 58  w_return_depth_shallow          2254 non-null   float64
 59  w_return_depth_deep             2254 non-null   float64
 60  w_return_depth_err_net          2254 non-null   float64
 61  w_return_depth_err_deep         2254 non-null   float64
 62  w_return_depth_err_wide         2254 non-null   float64
 63  w_return_depth_wide_deep        2254 non-null   float64
 64  w_shot_Direction_crosscourt     2258 non-null   int64
 65  w_shot_Direction_down_middle    2258 non-null   int64
 66  w_shot_Direction_down_the_line  2258 non-null   int64
 67  w_shot_Direction_inside_out     2258 non-null   int64
 68  w_shot_Direction_inside_in      2258 non-null   int64
 69  l_winners_fh                    2254 non-null   float64
 70  l_winners_bh                    2254 non-null   float64
 71  l_unforced_fh                   2254 non-null   float64
 72  l_unforced_bh                   2254 non-null   float64
 73  l_return_pts_faced              2254 non-null   float64
 74  l_return_pts_won                2254 non-null   float64
 75  l_return_depth_very_deep        2254 non-null   float64
 76  l_return_depth_shallow          2254 non-null   float64
 77  l_return_depth_deep             2254 non-null   float64
 78  l_return_depth_err_net          2254 non-null   float64
 79  l_return_depth_err_deep         2254 non-null   float64
 80  l_return_depth_err_wide         2254 non-null   float64
 81  l_return_depth_wide_deep        2254 non-null   float64
 82  l_shot_Direction_crosscourt     2257 non-null   float64
 83  l_shot_Direction_down_middle    2257 non-null   float64
 84  l_shot_Direction_down_the_line  2257 non-null   float64
 85  l_shot_Direction_inside_out     2257 non-null   float64
 86  l_shot_Direction_inside_in      2257 non-null   float64
dtypes: float64(65), int64(5), object(17)
memory usage: 1.5+ MB
None

In [73]:
sum(player1_merged['w_return_depth_err_wide'].isna()) 
# len(player1_merged['w_return_depth_err_wide'])

4

In [74]:
# overview_p2_w = pd.read_csv('../data/charting-m-stats-Overview.csv')

In [75]:
overview_p2_w[['tourney_date', 'sm', 'tourney_name', 'sm2', 'player1',
               'player2']] = overview_p2_w['match_id'].str.split('-', 6, expand=True)
overview_p2_w['tourney_date'] = overview_p2_w['tourney_date'].apply(
    lambda x: int(x))
overview_p2_w = overview_p2_w.loc[overview_p2_w['tourney_date'] > 20000000, :]
overview_p2_w = overview_p2_w[(overview_p2_w['set'] == 'Total') & (
    overview_p2_w['player'] == 1)]
overview_p2_w['l_1stIn'] = overview_p2_w['first_in']
overview_p2_w['l_1stWon'] = overview_p2_w['first_won']
overview_p2_w['l_2ndWon'] = overview_p2_w['second_won']
overview_p2_w['l_ace'] = overview_p2_w['aces']
overview_p2_w['l_winners_fh'] = overview_p2_w['winners_fh']
overview_p2_w['l_winners_bh'] = overview_p2_w['winners_bh']
overview_p2_w['l_unforced_fh'] = overview_p2_w['unforced_fh']
overview_p2_w['l_unforced_bh'] = overview_p2_w['unforced_bh']
overview_p2_w['l_return_pts_faced'] = overview_p2_w['return_pts']
overview_p2_w['l_return_pts_won'] = overview_p2_w['return_pts_won']
overview_p2_w['l_return_depth_very_deep'] = overview_p2_w['very_deep']
overview_p2_w['l_return_depth_shallow'] = overview_p2_w['shallow']
overview_p2_w['l_return_depth_deep'] = overview_p2_w['deep']
overview_p2_w['l_return_depth_err_net'] = overview_p2_w['err_net']
overview_p2_w['l_return_depth_err_deep'] = overview_p2_w['err_deep']
overview_p2_w['l_return_depth_err_wide'] = overview_p2_w['err_wide']
overview_p2_w['l_return_depth_wide_deep'] = overview_p2_w['err_wide_deep']
overview_p2_w['l_shot_Direction_crosscourt'] = overview_p2_w['crosscourt']
overview_p2_w['l_shot_Direction_down_middle'] = overview_p2_w['down_middle']
overview_p2_w['l_shot_Direction_down_the_line'] = overview_p2_w['down_the_line']
overview_p2_w['l_shot_Direction_inside_out'] = overview_p2_w['inside_out']
overview_p2_w['l_shot_Direction_inside_in'] = overview_p2_w['inside_in']
overview_p2_w.drop(overview_p2_w.columns.to_list()[1:37], axis=1, inplace=True)
overview_p2_w.rename(
    columns={'player1': 'loser_name', 'player2': 'winner_name'}, inplace=True)
overview_p2_w.loc[:, ['winner_name', 'loser_name']] = overview_p2_w.loc[:, [
    'winner_name', 'loser_name']].applymap(lambda x: x.replace('_', ' '))  # for multiple columns

In [76]:
overview_p2_w.head()

,match_id,loser_name,winner_name,l_1stIn,l_1stWon,l_2ndWon,l_ace,l_winners_fh,l_winners_bh,l_unforced_fh,...,l_return_depth_deep,l_return_depth_err_net,l_return_depth_err_deep,l_return_depth_err_wide,l_return_depth_wide_deep,l_shot_Direction_crosscourt,l_shot_Direction_down_middle,l_shot_Direction_down_the_line,l_shot_Direction_inside_out,l_shot_Direction_inside_in
98,20000612-M-Queens_Club-QF-Bob_Bryan-Pete_Sampras,Bob Bryan,Pete Sampras,40.0,27.0,13.0,9.0,4.0,4.0,4.0,...,7.0,0.0,0.0,0.0,0.0,8,9,5,5,0
100,20000910-M-US_Open-F-Pete_Sampras-Marat_Safin,Pete Sampras,Marat Safin,51.0,38.0,11.0,8.0,12.0,8.0,9.0,...,48.0,1.0,2.0,0.0,0.0,54,27,8,8,6
102,20001127-M-Tour_Finals-SF-Marat_Safin-Andre_Ag...,Marat Safin,Andre Agassi,34.0,22.0,13.0,4.0,5.0,13.0,14.0,...,40.0,0.0,1.0,0.0,0.0,106,45,34,8,1
104,20010312-M-Indian_Wells-QF-Nicolas_Lapentti-An...,Nicolas Lapentti,Andre Agassi,18.0,9.0,9.0,3.0,4.0,1.0,7.0,...,13.0,1.0,1.0,0.0,0.0,46,47,18,20,5
106,20010319-M-Miami_Masters-R32-Pete_Sampras-Andy...,Pete Sampras,Andy Roddick,42.0,30.0,11.0,8.0,6.0,6.0,9.0,...,18.0,0.0,0.0,0.0,0.0,22,5,9,8,1

In [77]:
overview_p1_w[['tourney_date', 'sm', 'tourney_name', 'sm2', 'player1',
               'player2']] = overview_p1_w['match_id'].str.split('-', 6, expand=True)
# df.rename(columns = {'first_in':'l_1stIn', 'first_won':'l_1stWon','second_won' : 'l_2ndWon', 'aces' : 'l_ace'}, inplace = True)
overview_p1_w['tourney_date'] = overview_p1_w['tourney_date'].apply(
    lambda x: int(x))
overview_p1_w = overview_p1_w.loc[overview_p1_w['tourney_date'] > 20000000, :]
overview_p1_w = overview_p1_w[(overview_p1_w['set'] == 'Total') & (
    overview_p1_w['player'] == 2)]
# df[df['l_1stIn' , 'l_1stWon','l_2ndWon' , 'l_ace']] = df['first_in', 'first_won','second_won' , 'aces' ]
overview_p1_w['w_1stIn'] = overview_p1_w['first_in']
overview_p1_w['w_1stWon'] = overview_p1_w['first_won']
overview_p1_w['w_2ndWon'] = overview_p1_w['second_won']
overview_p1_w['w_ace'] = overview_p1_w['aces']
overview_p1_w['w_winners_fh'] = overview_p1_w['winners_fh']
overview_p1_w['w_winners_bh'] = overview_p1_w['winners_bh']
overview_p1_w['w_unforced_fh'] = overview_p1_w['unforced_fh']
overview_p1_w['w_unforced_bh'] = overview_p1_w['unforced_bh']
overview_p1_w['w_return_pts_faced'] = overview_p1_w['return_pts']
overview_p1_w['w_return_pts_won'] = overview_p1_w['return_pts_won']
overview_p1_w['w_return_depth_very_deep'] = overview_p1_w['very_deep']
overview_p1_w['w_return_depth_shallow'] = overview_p1_w['shallow']
overview_p1_w['w_return_depth_deep'] = overview_p1_w['deep']
overview_p1_w['w_return_depth_err_net'] = overview_p1_w['err_net']
overview_p1_w['w_return_depth_err_deep'] = overview_p1_w['err_deep']
overview_p1_w['w_return_depth_err_wide'] = overview_p1_w['err_wide']
overview_p1_w['w_return_depth_wide_deep'] = overview_p1_w['err_wide_deep']
overview_p1_w['w_shot_Direction_crosscourt'] = overview_p1_w['crosscourt']
overview_p1_w['w_shot_Direction_down_middle'] = overview_p1_w['down_middle']
overview_p1_w['w_shot_Direction_down_the_line'] = overview_p1_w['down_the_line']
overview_p1_w['w_shot_Direction_inside_out'] = overview_p1_w['inside_out']
overview_p1_w['w_shot_Direction_inside_in'] = overview_p1_w['inside_in']
overview_p1_w.drop(overview_p1_w.columns.to_list()[1:37], axis=1, inplace=True)
overview_p1_w.rename(
    columns={'player1': 'loser_name', 'player2': 'winner_name'}, inplace=True)
overview_p1_w.loc[:, ['winner_name', 'loser_name']] = overview_p1_w.loc[:, [
    'winner_name', 'loser_name']].applymap(lambda x: x.replace('_', ' '))  # for multiple columns
overview_p1_w.head()

,match_id,loser_name,winner_name,w_1stIn,w_1stWon,w_2ndWon,w_ace,w_winners_fh,w_winners_bh,w_unforced_fh,...,w_return_depth_deep,w_return_depth_err_net,w_return_depth_err_deep,w_return_depth_err_wide,w_return_depth_wide_deep,w_shot_Direction_crosscourt,w_shot_Direction_down_middle,w_shot_Direction_down_the_line,w_shot_Direction_inside_out,w_shot_Direction_inside_in
99,20000612-M-Queens_Club-QF-Bob_Bryan-Pete_Sampras,Bob Bryan,Pete Sampras,26.0,24.0,14.0,6.0,14.0,18.0,1.0,...,12.0,0.0,1.0,0.0,0.0,16,7,1,4,1
101,20000910-M-US_Open-F-Pete_Sampras-Marat_Safin,Pete Sampras,Marat Safin,40.0,34.0,26.0,12.0,12.0,13.0,5.0,...,27.0,0.0,1.0,0.0,0.0,86,34,19,10,0
103,20001127-M-Tour_Finals-SF-Marat_Safin-Andre_Ag...,Marat Safin,Andre Agassi,38.0,31.0,15.0,5.0,11.0,7.0,7.0,...,34.0,1.0,0.0,1.0,1.0,126,35,19,14,1
105,20010312-M-Indian_Wells-QF-Nicolas_Lapentti-An...,Nicolas Lapentti,Andre Agassi,22.0,18.0,8.0,0.0,8.0,3.0,7.0,...,23.0,0.0,1.0,0.0,0.0,65,32,12,20,1
107,20010319-M-Miami_Masters-R32-Pete_Sampras-Andy...,Pete Sampras,Andy Roddick,40.0,35.0,12.0,7.0,13.0,5.0,3.0,...,26.0,0.0,0.0,0.0,0.0,30,13,5,15,2

In [78]:
overview_p2_w

,match_id,loser_name,winner_name,l_1stIn,l_1stWon,l_2ndWon,l_ace,l_winners_fh,l_winners_bh,l_unforced_fh,...,l_return_depth_deep,l_return_depth_err_net,l_return_depth_err_deep,l_return_depth_err_wide,l_return_depth_wide_deep,l_shot_Direction_crosscourt,l_shot_Direction_down_middle,l_shot_Direction_down_the_line,l_shot_Direction_inside_out,l_shot_Direction_inside_in
98,20000612-M-Queens_Club-QF-Bob_Bryan-Pete_Sampras,Bob Bryan,Pete Sampras,40.0,27.0,13.0,9.0,4.0,4.0,4.0,...,7.0,0.0,0.0,0.0,0.0,8,9,5,5,0
100,20000910-M-US_Open-F-Pete_Sampras-Marat_Safin,Pete Sampras,Marat Safin,51.0,38.0,11.0,8.0,12.0,8.0,9.0,...,48.0,1.0,2.0,0.0,0.0,54,27,8,8,6
102,20001127-M-Tour_Finals-SF-Marat_Safin-Andre_Ag...,Marat Safin,Andre Agassi,34.0,22.0,13.0,4.0,5.0,13.0,14.0,...,40.0,0.0,1.0,0.0,0.0,106,45,34,8,1
104,20010312-M-Indian_Wells-QF-Nicolas_Lapentti-An...,Nicolas Lapentti,Andre Agassi,18.0,9.0,9.0,3.0,4.0,1.0,7.0,...,13.0,1.0,1.0,0.0,0.0,46,47,18,20,5
106,20010319-M-Miami_Masters-R32-Pete_Sampras-Andy...,Pete Sampras,Andy Roddick,42.0,30.0,11.0,8.0,6.0,6.0,9.0,...,18.0,0.0,0.0,0.0,0.0,22,5,9,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5237,20220704-M-Wimbledon-R16-Rafael_Nadal-Botic_Va...,Rafael Nadal,Botic Van De Zandschulp,56.0,41.0,21.0,8.0,8.0,11.0,13.0,...,50.0,0.0,0.0,3.0,1.0,67,50,22,21,2
5241,20220712-M-Newport-R32-Andy_Murray-Sam_Querrey,Andy Murray,Sam Querrey,31.0,21.0,7.0,5.0,2.0,2.0,2.0,...,15.0,1.0,0.0,0.0,0.0,17,28,7,5,0
5243,20220712-M-Bastad-R32-Emil_Ruusuvuori-Dominic_...,Emil Ruusuvuori,Dominic Thiem,55.0,31.0,18.0,1.0,11.0,6.0,15.0,...,53.0,0.0,2.0,0.0,0.0,148,90,30,40,3
5245,20220706-M-Wimbledon-QF-Nick_Kyrgios-Cristian_...,Nick Kyrgios,Cristian Garin,81.0,59.0,14.0,17.0,11.0,4.0,21.0,...,0.0,0.0,3.0,0.0,0.0,44,99,14,34,0
5247,20220713-M-Newport-R16-Andy_Murray-Max_Purcell,Andy Murray,Max Purcell,50.0,35.0,16.0,8.0,10.0,7.0,11.0,...,45.0,0.0,0.0,0.0,0.0,131,60,35,39,7

In [79]:
overview_clean2 = pd.merge(overview_p1_w,
                           overview_p2_w,
                           on=['winner_name', 'loser_name', 'match_id'],
                           how="outer")

player2_merged = pd.merge(first_repo_data,
                          overview_clean2,
                          on=['l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_ace', 'winner_name',
                              'loser_name', 'w_1stIn', 'w_1stWon', 'w_2ndWon', 'w_ace'],
                          how="right")
player2_merged = player2_merged.dropna(subset=['l_bpSaved'])
player2_merged.reset_index(inplace=True)
# first player wins so label=1
winner_player2 = np.zeros(player2_merged.shape[0])
player2_merged['label'] = winner_player2
display(player2_merged.head())
display(player2_merged.info())
player2_merged.to_csv('../data/second-ATP.csv')

,index,Unnamed: 0,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,...,l_return_depth_err_net,l_return_depth_err_deep,l_return_depth_err_wide,l_return_depth_wide_deep,l_shot_Direction_crosscourt,l_shot_Direction_down_middle,l_shot_Direction_down_the_line,l_shot_Direction_inside_out,l_shot_Direction_inside_in,label
0,32,7324.0,2007-352,Paris Masters,Hard,48.0,M,20071028.0,47.0,103900.0,...,0.0,1.0,0.0,0.0,65,29,22,17,2,0.0
1,56,17728.0,2010-540,Wimbledon,Grass,128.0,G,20100621.0,127.0,104745.0,...,0.0,1.0,0.0,0.0,77,45,21,34,4,0.0
2,62,19594.0,2011-495,Dubai,Hard,32.0,A,20110221.0,31.0,104925.0,...,0.0,1.0,0.0,0.0,55,34,15,30,3,0.0
3,70,20454.0,2011-520,Roland Garros,Clay,128.0,G,20110522.0,127.0,104745.0,...,1.0,3.0,2.0,0.0,163,104,56,63,8,0.0
4,93,23135.0,2012-410,Monte Carlo Masters,Clay,56.0,M,20120415.0,55.0,104745.0,...,0.0,1.0,0.0,0.0,63,66,20,46,4,0.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Data columns (total 89 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   index                           326 non-null    int64
 1   Unnamed: 0                      326 non-null    float64
 2   tourney_id                      326 non-null    object
 3   tourney_name                    326 non-null    object
 4   surface                         326 non-null    object
 5   draw_size                       326 non-null    float64
 6   tourney_level                   326 non-null    object
 7   tourney_date                    326 non-null    float64
 8   match_num                       326 non-null    float64
 9   winner_id                       326 non-null    float64
 10  winner_seed                     209 non-null    object
 11  winner_entry                    39 non-null     object
 12  winner_name                     326 non-null    object
 13  winner_hand                     326 non-null    object
 14  winner_ht                       325 non-null    float64
 15  winner_ioc                      326 non-null    object
 16  winner_age                      326 non-null    float64
 17  loser_id                        326 non-null    float64
 18  loser_seed                      184 non-null    object
 19  loser_entry                     41 non-null     object
 20  loser_name                      326 non-null    object
 21  loser_hand                      326 non-null    object
 22  loser_ht                        323 non-null    float64
 23  loser_ioc                       326 non-null    object
 24  loser_age                       326 non-null    float64
 25  score                           326 non-null    object
 26  best_of                         326 non-null    float64
 27  round                           326 non-null    object
 28  minutes                         319 non-null    float64
 29  w_ace                           326 non-null    float64
 30  w_df                            326 non-null    float64
 31  w_svpt                          326 non-null    float64
 32  w_1stIn                         326 non-null    float64
 33  w_1stWon                        326 non-null    float64
 34  w_2ndWon                        326 non-null    float64
 35  w_SvGms                         326 non-null    float64
 36  w_bpSaved                       326 non-null    float64
 37  w_bpFaced                       326 non-null    float64
 38  l_ace                           326 non-null    float64
 39  l_df                            326 non-null    float64
 40  l_svpt                          326 non-null    float64
 41  l_1stIn                         326 non-null    float64
 42  l_1stWon                        326 non-null    float64
 43  l_2ndWon                        326 non-null    float64
 44  l_SvGms                         326 non-null    float64
 45  l_bpSaved                       326 non-null    float64
 46  l_bpFaced                       326 non-null    float64
 47  winner_rank                     326 non-null    float64
 48  winner_rank_points              326 non-null    float64
 49  loser_rank                      325 non-null    float64
 50  loser_rank_points               325 non-null    float64
 51  match_id                        326 non-null    object
 52  w_winners_fh                    326 non-null    float64
 53  w_winners_bh                    326 non-null    float64
 54  w_unforced_fh                   326 non-null    float64
 55  w_unforced_bh                   326 non-null    float64
 56  w_return_pts_faced              326 non-null    float64
 57  w_return_pts_won                326 non-null    float64
 58  w_return_depth_very_deep        326 non-null    float64
 59  w_return_depth_shallow          326 non-null    float64
 60  w_return_depth_deep             326 non-null    float64
 61  w_return_depth_err_net          326 non-null    float64
 62  w_return_depth_err_deep         326 non-null    float64
 63  w_return_depth_err_wide         326 non-null    float64
 64  w_return_depth_wide_deep        326 non-null    float64
 65  w_shot_Direction_crosscourt     326 non-null    float64
 66  w_shot_Direction_down_middle    326 non-null    float64
 67  w_shot_Direction_down_the_line  326 non-null    float64
 68  w_shot_Direction_inside_out     326 non-null    float64
 69  w_shot_Direction_inside_in      326 non-null    float64
 70  l_winners_fh                    326 non-null    float64
 71  l_winners_bh                    326 non-null    float64
 72  l_unforced_fh                   326 non-null    float64
 73  l_unforced_bh                   326 non-null    float64
 74  l_return_pts_faced              326 non-null    float64
 75  l_return_pts_won                326 non-null    float64
 76  l_return_depth_very_deep        326 non-null    float64
 77  l_return_depth_shallow          326 non-null    float64
 78  l_return_depth_deep             326 non-null    float64
 79  l_return_depth_err_net          326 non-null    float64
 80  l_return_depth_err_deep         326 non-null    float64
 81  l_return_depth_err_wide         326 non-null    float64
 82  l_return_depth_wide_deep        326 non-null    float64
 83  l_shot_Direction_crosscourt     326 non-null    int64
 84  l_shot_Direction_down_middle    326 non-null    int64
 85  l_shot_Direction_down_the_line  326 non-null    int64
 86  l_shot_Direction_inside_out     326 non-null    int64
 87  l_shot_Direction_inside_in      326 non-null    int64
 88  label                           326 non-null    float64
dtypes: float64(66), int64(6), object(17)
memory usage: 226.8+ KB

None

In [2]:
first_ATP = pd.read_csv('../data/first-ATP.csv')
second_ATP = pd.read_csv('../data/second-ATP.csv')
full_data = pd.concat([second_ATP, first_ATP], ignore_index=True)
full_data.drop(['Unnamed: 0.1', 'Unnamed: 0', 'index'], axis=1, inplace=True)

In [14]:
l = full_data.columns.tolist()
def change(x) : 
    if x.startswith('w_'): 
        i = x[0:2]
        result = x.replace(i,'fp_')
        return result
    elif x.startswith('l_'): 
        i = x[0:2]
        result = x.replace(i,'sp_')
        return result  
    elif x.startswith('winner'): 
        i = x[0:6]
        result = x.replace(i,'FirstPlayer')
        return result 
    elif x.startswith('loser_'): 
        i = x[0:5]
        result = x.replace(i,'SecondPlayer_')
        return result 
    else : 
        return x 
full_data.columns = list(map(change, l))
print(full_data.columns.tolist())

['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level', 'tourney_date', 'match_num', 'FirstPlayer_id', 'FirstPlayer_seed', 'FirstPlayer_entry', 'FirstPlayer_name', 'FirstPlayer_hand', 'FirstPlayer_ht', 'FirstPlayer_ioc', 'FirstPlayer_age', 'SecondPlayerr_id', 'SecondPlayerr_seed', 'SecondPlayerr_entry', 'SecondPlayerr_name', 'SecondPlayerr_hand', 'SecondPlayerr_ht', 'SecondPlayerr_ioc', 'SecondPlayerr_age', 'score', 'best_of', 'round', 'minutes', 'fp_ace', 'fp_df', 'fp_svpt', 'fp_1stIn', 'fp_1stWon', 'fp_2ndWon', 'fp_SvGms', 'fp_bpSaved', 'fp_bpFaced', 'sp_ace', 'sp_df', 'sp_svpt', 'sp_1stIn', 'sp_1stWon', 'sp_2ndWon', 'sp_SvGms', 'sp_bpSaved', 'sp_bpFaced', 'FirstPlayer_rank', 'FirstPlayer_rank_points', 'SecondPlayerr_rank', 'SecondPlayerr_rank_points', 'match_id', 'fp_winners_fh', 'fp_winners_bh', 'fp_unforced_fh', 'fp_unforced_bh', 'fp_return_pts_faced', 'fp_return_pts_won', 'fp_return_depth_very_deep', 'fp_return_depth_shallow', 'fp_return_depth_deep', 'fp_return_depth_err_net', 'fp_return_depth_err_deep', 'fp_return_depth_err_wide', 'fp_return_depth_wide_deep', 'fp_shot_Direction_crosscourt', 'fp_shot_Direction_down_middle', 'fp_shot_Direction_down_the_line', 'fp_shot_Direction_inside_out', 'fp_shot_Direction_inside_in', 'sp_winners_fh', 'sp_winners_bh', 'sp_unforced_fh', 'sp_unforced_bh', 'sp_return_pts_faced', 'sp_return_pts_won', 'sp_return_depth_very_deep', 'sp_return_depth_shallow', 'sp_return_depth_deep', 'sp_return_depth_err_net', 'sp_return_depth_err_deep', 'sp_return_depth_err_wide', 'sp_return_depth_wide_deep', 'sp_shot_Direction_crosscourt', 'sp_shot_Direction_down_middle', 'sp_shot_Direction_down_the_line', 'sp_shot_Direction_inside_out', 'sp_shot_Direction_inside_in', 'label']

In [15]:
full_data = full_data.dropna(subset=['tourney_id'])
full_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 649 entries, 0 to 2580
Data columns (total 87 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   tourney_id                       649 non-null    object
 1   tourney_name                     649 non-null    object
 2   surface                          649 non-null    object
 3   draw_size                        649 non-null    float64
 4   tourney_level                    649 non-null    object
 5   tourney_date                     649 non-null    float64
 6   match_num                        649 non-null    float64
 7   FirstPlayer_id                   649 non-null    float64
 8   FirstPlayer_seed                 436 non-null    object
 9   FirstPlayer_entry                66 non-null     object
 10  FirstPlayer_name                 649 non-null    object
 11  FirstPlayer_hand                 649 non-null    object
 12  FirstPlayer_ht                   648 non-null    float64
 13  FirstPlayer_ioc                  649 non-null    object
 14  FirstPlayer_age                  649 non-null    float64
 15  SecondPlayerr_id                 649 non-null    float64
 16  SecondPlayerr_seed               340 non-null    object
 17  SecondPlayerr_entry              84 non-null     object
 18  SecondPlayerr_name               649 non-null    object
 19  SecondPlayerr_hand               649 non-null    object
 20  SecondPlayerr_ht                 643 non-null    float64
 21  SecondPlayerr_ioc                649 non-null    object
 22  SecondPlayerr_age                649 non-null    float64
 23  score                            649 non-null    object
 24  best_of                          649 non-null    float64
 25  round                            649 non-null    object
 26  minutes                          623 non-null    float64
 27  fp_ace                           648 non-null    float64
 28  fp_df                            648 non-null    float64
 29  fp_svpt                          648 non-null    float64
 30  fp_1stIn                         648 non-null    float64
 31  fp_1stWon                        648 non-null    float64
 32  fp_2ndWon                        648 non-null    float64
 33  fp_SvGms                         648 non-null    float64
 34  fp_bpSaved                       648 non-null    float64
 35  fp_bpFaced                       648 non-null    float64
 36  sp_ace                           648 non-null    float64
 37  sp_df                            648 non-null    float64
 38  sp_svpt                          648 non-null    float64
 39  sp_1stIn                         648 non-null    float64
 40  sp_1stWon                        648 non-null    float64
 41  sp_2ndWon                        648 non-null    float64
 42  sp_SvGms                         648 non-null    float64
 43  sp_bpSaved                       648 non-null    float64
 44  sp_bpFaced                       648 non-null    float64
 45  FirstPlayer_rank                 649 non-null    float64
 46  FirstPlayer_rank_points          649 non-null    float64
 47  SecondPlayerr_rank               648 non-null    float64
 48  SecondPlayerr_rank_points        648 non-null    float64
 49  match_id                         649 non-null    object
 50  fp_winners_fh                    648 non-null    float64
 51  fp_winners_bh                    648 non-null    float64
 52  fp_unforced_fh                   648 non-null    float64
 53  fp_unforced_bh                   648 non-null    float64
 54  fp_return_pts_faced              648 non-null    float64
 55  fp_return_pts_won                648 non-null    float64
 56  fp_return_depth_very_deep        648 non-null    float64
 57  fp_return_depth_shallow          648 non-null    float64
 58  fp_return_depth_deep             648 non-null    float64
 59  fp_return_depth_err_net          648 non-null    float64
 60  fp_return_depth_err_deep         648 non-null    float64
 61  fp_return_depth_err_wide         648 non-null    float64
 62  fp_return_depth_wide_deep        648 non-null    float64
 63  fp_shot_Direction_crosscourt     649 non-null    float64
 64  fp_shot_Direction_down_middle    649 non-null    float64
 65  fp_shot_Direction_down_the_line  649 non-null    float64
 66  fp_shot_Direction_inside_out     649 non-null    float64
 67  fp_shot_Direction_inside_in      649 non-null    float64
 68  sp_winners_fh                    648 non-null    float64
 69  sp_winners_bh                    648 non-null    float64
 70  sp_unforced_fh                   648 non-null    float64
 71  sp_unforced_bh                   648 non-null    float64
 72  sp_return_pts_faced              648 non-null    float64
 73  sp_return_pts_won                648 non-null    float64
 74  sp_return_depth_very_deep        648 non-null    float64
 75  sp_return_depth_shallow          648 non-null    float64
 76  sp_return_depth_deep             648 non-null    float64
 77  sp_return_depth_err_net          648 non-null    float64
 78  sp_return_depth_err_deep         648 non-null    float64
 79  sp_return_depth_err_wide         648 non-null    float64
 80  sp_return_depth_wide_deep        648 non-null    float64
 81  sp_shot_Direction_crosscourt     649 non-null    float64
 82  sp_shot_Direction_down_middle    649 non-null    float64
 83  sp_shot_Direction_down_the_line  649 non-null    float64
 84  sp_shot_Direction_inside_out     649 non-null    float64
 85  sp_shot_Direction_inside_in      649 non-null    float64
 86  label                            649 non-null    float64
dtypes: float64(70), object(17)
memory usage: 446.2+ KB

In [ ]:
# What is the avreage highet for the top plyers 
# what is the favoate hand 
# what is the average scores 
# what is their wining precentage on every surface

In [16]:
top_data = full_data.loc[ (full_data['FirstPlayer_rank'] < 20) | (full_data['SecondPlayerr_rank'] < 20) , :]

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,FirstPlayer_id,FirstPlayer_seed,FirstPlayer_entry,...,sp_return_depth_err_net,sp_return_depth_err_deep,sp_return_depth_err_wide,sp_return_depth_wide_deep,sp_shot_Direction_crosscourt,sp_shot_Direction_down_middle,sp_shot_Direction_down_the_line,sp_shot_Direction_inside_out,sp_shot_Direction_inside_in,label
0,2007-352,Paris Masters,Hard,48.0,M,20071028.0,47.0,103900.0,NaN,NaN,...,0.0,1.0,0.0,0.0,65.0,29.0,22.0,17.0,2.0,0.0
1,2010-540,Wimbledon,Grass,128.0,G,20100621.0,127.0,104745.0,2.0,NaN,...,0.0,1.0,0.0,0.0,77.0,45.0,21.0,34.0,4.0,0.0
2,2011-495,Dubai,Hard,32.0,A,20110221.0,31.0,104925.0,2.0,NaN,...,0.0,1.0,0.0,0.0,55.0,34.0,15.0,30.0,3.0,0.0
3,2011-520,Roland Garros,Clay,128.0,G,20110522.0,127.0,104745.0,1.0,NaN,...,1.0,3.0,2.0,0.0,163.0,104.0,56.0,63.0,8.0,0.0
4,2012-410,Monte Carlo Masters,Clay,56.0,M,20120415.0,55.0,104745.0,2.0,NaN,...,0.0,1.0,0.0,0.0,63.0,66.0,20.0,46.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2502,2022-1536,Madrid Masters,Clay,64.0,M,20220502.0,300.0,207989.0,7,NaN,...,0.0,1.0,0.0,0.0,21.0,41.0,5.0,16.0,0.0,1.0
2509,2022-0416,Rome Masters,Clay,64.0,M,20220509.0,285.0,104925.0,1,NaN,...,0.0,2.0,0.0,0.0,61.0,74.0,4.0,33.0,1.0,1.0
2522,2022-0416,Rome Masters,Clay,64.0,M,20220509.0,297.0,104925.0,1,NaN,...,0.0,0.0,0.0,0.0,83.0,77.0,24.0,27.0,3.0,1.0
2533,2022-0322,Geneva,Clay,32.0,A,20220516.0,286.0,134770.0,2,NaN,...,5.0,1.0,0.0,0.0,24.0,31.0,3.0,20.0,0.0,1.0
2577,2022-540,Wimbledon,Grass,128.0,G,20220627.0,212.0,104925.0,1,NaN,...,4.0,2.0,1.0,0.0,124.0,73.0,30.0,25.0,5.0,1.0

In [17]:
import matplotlib.pyplot as plt
import seaborn as sns